// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBEySG0OtetIEDv945L8fDSRXnvRGbr-lQ',
    appId: '1:832798832601:web:3ecb95e729e6a686604bc8',
    messagingSenderId: '832798832601',
    projectId: 'rivergram',
    authDomain: 'rivergram.firebaseapp.com',
    storageBucket: 'rivergram.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBIZb7yvLN_tD_w8GTHWJqSTaa5g149X6o',
    appId: '1:832798832601:android:1470d3ef0ab56f81604bc8',
    messagingSenderId: '832798832601',
    projectId: 'rivergram',
    storageBucket: 'rivergram.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDM-dqWPff9j-kpeEb0d7gZkquXq4MjeXU',
    appId: '1:832798832601:ios:e7cc4e6bfcd6c465604bc8',
    messagingSenderId: '832798832601',
    projectId: 'rivergram',
    storageBucket: 'rivergram.appspot.com',
    iosClientId:
        '832798832601-ql13f5uot0nvti7mqkp4spc02k7etk78.apps.googleusercontent.com',
    iosBundleId: 'com.example.rivergram',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDM-dqWPff9j-kpeEb0d7gZkquXq4MjeXU',
    appId: '1:832798832601:ios:e7cc4e6bfcd6c465604bc8',
    messagingSenderId: '832798832601',
    projectId: 'rivergram',
    storageBucket: 'rivergram.appspot.com',
    iosClientId:
        '832798832601-ql13f5uot0nvti7mqkp4spc02k7etk78.apps.googleusercontent.com',
    iosBundleId: 'com.example.rivergram',
  );
}
